### ISSUE TITLE
InvalidOperationException at startup

### ISSUE THREAD

**Issue by DemiMarie** [reactjs/React.NET#601]
When running my code, I get a `System.InvalidOperationException` at startup.  How can I debug this?

**Comment by DemiMarie** [comment]
Partial stack trace:

```
Exception has occurred: CLR/System.InvalidOperationException
An exception of type 'System.InvalidOperationException' occurred in Microsoft.Extensions.DependencyInjection.dll but was not handled in user code: 'Cannot resolve scoped service 'React.AspNet.HttpContextLifetimeProvider+PerRequestRegistrations' from root provider.'
  at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor.ValidateResolution(Type serviceType, IServiceScope scope, IServiceScope rootScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, IServiceScope scope)
```
(some frames skipped)
```
   at React.AspNet.ReactBuilderExtensions.EnsureServicesRegistered(IApplicationBuilder app)
   at React.AspNet.ReactBuilderExtensions.UseReact(IApplicationBuilder app, Action`1 configure, BabelFileOptions fileOptions)
```

**Comment by nightblade9** [comment]
I, too, get this with ASP.NET Core 2.1. This is similar to [this issue](https://github.com/reactjs/React.NET/issues/433), which talks about (and fixes) ASP.NET Core 2.0; the proposed fix doesn't work on 2.1; you get this error instead:

```
InvalidOperationException: The 'Configure' method in the type 'ReactDemo.Startup' must have a return type of 'Void'.

Microsoft.AspNetCore.Hosting.Internal.StartupLoader.FindMethod(Type startupType, string methodName, string environmentName, Type returnType, bool required)
```

**Comment by DemiMarie** [comment]
Do you know any workarounds?

**Comment by nightblade9** [comment]
@DemiMarie no, I haven't figured out any work-around yet. I tried installing the .NET Core 2.0 SDK, hoping Visual Studio would use that instead, but it doesn't; I get a compile-time error when I downgrade my project to 2.0, about some library that's .NET Core 2.1, but not referenced in NuGet etc.

**Comment by dustinsoftware** [comment]
Thanks for reporting, I’ll give this a look

**Comment by jbrinkle** [comment]
@DemiMarie @nightblade9 
I got the same behavior while starting a brand new Core 2.1 AspNet MVC web app.
However, I _also_ followed the [migratory steps from Core 2.0 to 2.1](https://docs.microsoft.com/en-us/aspnet/core/migration/20_21?view=aspnetcore-2.1#update-the-project-file-to-use-21-versions) on the tutorial project and it worked. I don't know why, but you may be able to reference the same page in your efforts to reverse-migrate back to 2.0

**Comment by nightblade9** [comment]
Interestingly,Visual Studio now includes a template for a "React" app. I don't think it's ReactJS.NET, I think it's just vanilla React; that template seems to run fine.

**Comment by nightblade9** [comment]
I did some more digging with the .NET Core 2.1 template.

If you add this code to the `ConfigureServices` method, not with `Configure` as the tutorial specifies:

```
services.AddSingleton<IHttpContextAccessor, HttpContextAccessor>();
services.AddReact();
```

You get an exception on the `app.UseReact(config =>` line. The exception is:

```
InvalidOperationException: Cannot resolve scoped service 'React.AspNet.HttpContextLifetimeProvider+PerRequestRegistrations' from root provider.
```

It looks like `HttpContextLifetimeProvider` is an internal class defined [here](https://github.com/reactjs/React.NET/blob/5cbcd22e09444086401d51e65653505d49734146/src/React.AspNet.Middleware/HttpContextLifetimeProvider.cs), and this is something `AddReact` is supposed to add.

I added debugger points to make sure `AddReact` is being hit, and it is.

Can someone from the ReactJS.NET core team help?

**Comment by dustinsoftware** [comment]
I just tried to update one of the samples to .NET Core 2.1 and had no problems.. 

Can you give this sample a look? I don't have time right now to investigate further. https://github.com/reactjs/React.NET/blob/master/src/React.Sample.CoreMvc/React.Sample.CoreMvc.csproj

**Comment by DaniilSokolyuk** [comment]
I think because https://github.com/reactjs/React.NET/blob/fe72ea9ca18793fea75282f0514e969384853d5e/src/React.Sample.CoreMvc/Startup.cs#L37 returns IServiceProvider, but! in default template it returns void.
You can disable DI Scope validation and fix this problem, in program.cs 
`  public static IWebHostBuilder CreateWebHostBuilder(string[] args) =>
            WebHost.CreateDefaultBuilder(args)
                .UseDefaultServiceProvider(options => options.ValidateScopes = false) // << add this line
                .UseStartup<Startup>();`

**Comment by dustinsoftware** [comment]
@DaniilSokolyuk is correct, returning an instance of `IServiceProvider` is necessary. I'm not sure why this is the case, and it appears the docs are out of date. We may need to change how we're building a service provider since all the .NET Core docs indicate that `ConfigureServices` have no return value.

**Comment by dustinsoftware** [comment]
Huh, looks like the problem is resolved by removing the `EnsureServicesRegistered` check in `ReactBuilderExtensions`. I'll do a little bit more testing to ensure we can remove it safely.

**Comment by dustinsoftware** [comment]
This has been fixed in the latest release of ReactJS.NET.

**Comment by dustinsoftware** [comment]
My mistake, hadn't pushed the fix yet. Will go out with the next release.

**Comment by Benja-blip** [comment]
This problem still persists with Core 3.0. I changed the ConfigureServices from `public void` to `public IServiceProvder`  and with `return services.BuildServiceProvider();` but I get the following error:

ConfigureServices returning an System.IServiceProvider isn't supported -- which is apparently a new thing with Core 3.0? Problem is I have no idea what the fix is for React.AspNet...

I also tried `.UseDefaultServiceProvider(options => options.ValidateScopes = false)` in the Program.cs file, but then it threw this exception:

Method 'InnerEvaluate' in type 'React.VroomJsEngine' from assembly 'React.Core, Version=3.0.0.0, Culture=neutral, PublicKeyToken=9aed67b161f7db78' does not have an implementation.

Am I missing something?
